# Generated by Django 3.1.12 on 2022-06-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0062_auto_20220118_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='novel',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='novelviews',
            name='viewsNovelName',
            field=models.SlugField(default='', max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reported_by', 'chapter', 'description')},
        ),
    ]
