# Generated by Django 3.1.12 on 2022-08-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0063_auto_20220616_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novel'),
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='request_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RJ', 'Rejected'), ('AP', 'Approved'), ('AC', 'Approved and Closed'), ('II', 'Incomplete Info Provided')], default='PD', max_length=2),
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('NA', 'Novel Add'), ('CR', 'Chapter Report'), ('NR', 'Novel Report')], default='CR', max_length=2),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='report',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
