# Generated by Django 3.1.12 on 2022-09-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0065_chapter_is_eighteen'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='dmca',
            field=models.BooleanField(default=False),
        ),
    ]
